### ISSUE TITLE
Can't train YOLO in GoogleColab

### ISSUE THREAD

**Issue by martisaju** [ivangrov/YOLOv3-GoogleColab#1]
Hi Ivan!
I'm new in Google Colab and I'm having some problems to train my YOLO network with my custom data.

I am executing:
!./darknet detector train data/obj.data yolov3-tiny-obj.cfg yolov3-tiny.conv.15 -dont_show
inside x64 folder and I figure the following error:

![screenshot_error](https://user-images.githubusercontent.com/29142274/52968479-9a253800-33ad-11e9-80ff-fc34ebe26978.JPG)

Please, can you help me?

Thank you so much and congrats for all your work :)

**Comment by aadeshb7** [comment]
have you used all the steps described by ivan?? and are you using alexey ab repository?

**Comment by martisaju** [comment]
Hi!
Yes, I used all the steps described by Ivan there: https://github.com/ivangrov/YOLOv3-GoogleColab/blob/master/YOLOv3_GoogleColab.ipynb and also I have reinstalled it again.

The problem I had when I was installing it, it was when he comments:
"#ATTENTION! AT THIS POINT YOU'VE INSTALLED DARKNET AND IF YOU SEE THE IMAGE, IT WORKS! SO FROM NOW ON THE REST OF THE NOTEBOOK IS MADE OF TIPS AND TRICKS, AND COMMENTED CODE
#THAT I USED MYSELF, SO HERE YOU WANNA PUT EVERYTHING TOGETHER ACCORDING TO YOUR NEEDS, YOU KNOW"

And the above code until:

"#Okay, so if you're familiar with AlexeyAB's darknet fork you know that we'll
#need 5 things:
..."
If I am not wrong, what I had just to import is my **obj folder** (where I have the data) into build/x64/data folder, the **train.txt** file, **obj.data** and **obj.names** file at the same folder. Also, in folder x64 I imported the following files: **yolov3-tiny.conv.15, yolov3-tiny.weights, yolov3-tiny-obj.cfg**

Do you think I have made something wrong?

Thank you so much.

**Comment by aadeshb7** [comment]
yes...you did it right..but dont place your files in x64 folder...place them in the darknet folder...that is the first folder itself which contains the build and other folders...

**Comment by martisaju** [comment]
Hi, 
It worked! Thank you so much @aadeshb7 !
