### ISSUE TITLE
Can't detect Custom Objects

### ISSUE THREAD

**Issue by martisaju** [ivangrov/YOLOv3-GoogleColab#2]
Hello!
I am trying to detect my custom objects but my YOLO network traning process takes a lot of time. I am doing it with Google Colab and it loses its connection before the convergence of the loss function (after 6000 iterations) so it can 't detect any object...

Do you know how can I solve that problem?

Also I have a doubt that maybe that's the reason of my problem: When I upload the training images with their corresponding bounding box I don't use entire images, I just upload images of the object I want to detect (with their bounding box):

i.e.

![captura](https://user-images.githubusercontent.com/29142274/53886826-2cba0e00-4021-11e9-965d-1b8143b4d8bf.JPG)

instead of:

![30](https://user-images.githubusercontent.com/29142274/53886830-32175880-4021-11e9-9183-e2130f708e7f.jpg)

Could it be the reason of my problem?

Thank you so much

**Comment by StefanPushkov** [comment]
@martisaju, hello! How did you solve the problem? Did you train the model from scratch or used transfer learning?
